import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ttFirsNeue = localFont({
  src: "./font/tt_firs_neue/TT_Firs_Neue_Trial_Regular.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: "Gospel Events God Bless You",
  url: "https://gospel-events.fr",
  image: "/logo.png",
  description: "presentation de Gospel Events God Bless You, nos formules, notre histoire, formulaire pour nous contacter",
  address: {
    "@type": "PostalAddress",
    "streetAddress": "76 RUE DU GODET",
    "addressLocality": "CHECY",
    "addressCountry": "FR",
    "addressRegion": "Centre-Val de Loire",
    "postalCode": "45430"
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <link rel="icon" href="/logo.ico" sizes="any" />
        <meta name="robots" content="notdm" />
        <meta name="tdm-reservation" content="1" />
      </head>
      <body className={`${ttFirsNeue.className} antialiased`}>{children}</body>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
    </html>
  );
}
